---
# Note: None of these examples set subscription_id or management_cert_path
# It is assumed that their matching environment variables are set.

- hosts: localhost
  gather_facts: False
  tasks:

# Provision virtual machine example
  - name: provision Azure VM
    local_action:
      module: azure
      name: circuitpuppet
      role_size: Basic_A0
      image: 5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-70-20140926
      location: 'North Central US'
      user: circuit
      ssh_cert_path: /home/swindmill/azure/ssh.pem
      storage_account: circuits
      wait: yes
      endpoints: 22,80
    register: azure

  - name: show azure output
    debug: msg="{{ azure }}"

  - name: wait for SSH
    local_action: wait_for port=22 host={{ azure.public_dns_name }} search_regex=OpenSSH

  - name: add instance for further management
    local_action: add_host hostname={{ azure.public_dns_name }} groupname=launched

- hosts: launched
  sudo: yes
  user: circuit

  tasks:

  - name: setup yum repos
    yum: name="{{ item }}"
    with_items:
      - http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
      - http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
      - http://yum.theforeman.org/releases/1.6/el7/x86_64/foreman-release.rpm

  - name: setup foreman SCL repo
    yum: name=foreman-release-scl disable_gpg_check=yes

  - name: install foreman-installer
    yum: name=foreman-installer

  - name: add to hosts file
    lineinfile: dest=/etc/hosts line="{{ ansible_eth0.ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}" 

  - name: disable firewall
    service: name=firewalld state=stopped enabled=no

#  - name: install foreman
#    command: "foreman-installer --foreman-configure-scl-repo=false"
